<?php

namespace ContainerGCMjFn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I6OO7qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i6_OO7q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i6_OO7q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PlatController::addPlat' => ['privates', '.service_locator.A_mc0BP', 'get_ServiceLocator_AMc0BPService', true],
            'App\\Controller\\PlatController::deletePlat' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\PlatController::index' => ['privates', '.service_locator.A_mc0BP', 'get_ServiceLocator_AMc0BPService', true],
            'App\\Controller\\PlatController::showPlat' => ['privates', '.service_locator.A_mc0BP', 'get_ServiceLocator_AMc0BPService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PlatController:addPlat' => ['privates', '.service_locator.A_mc0BP', 'get_ServiceLocator_AMc0BPService', true],
            'App\\Controller\\PlatController:deletePlat' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\PlatController:index' => ['privates', '.service_locator.A_mc0BP', 'get_ServiceLocator_AMc0BPService', true],
            'App\\Controller\\PlatController:showPlat' => ['privates', '.service_locator.A_mc0BP', 'get_ServiceLocator_AMc0BPService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PlatController::addPlat' => '?',
            'App\\Controller\\PlatController::deletePlat' => '?',
            'App\\Controller\\PlatController::index' => '?',
            'App\\Controller\\PlatController::showPlat' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PlatController:addPlat' => '?',
            'App\\Controller\\PlatController:deletePlat' => '?',
            'App\\Controller\\PlatController:index' => '?',
            'App\\Controller\\PlatController:showPlat' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
