version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php73
    depends_on:
      - db
    image: php:7.3-apache
    volumes:
      - ./php:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: restaurant
      MYSQL_DATABASE: restaurant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 20M
    ports:
    - 8899:80