<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGCMjFn1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGCMjFn1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGCMjFn1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGCMjFn1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGCMjFn1\App_KernelDevDebugContainer([
    'container.build_hash' => 'GCMjFn1',
    'container.build_id' => 'dac747ea',
    'container.build_time' => 1675854737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGCMjFn1');
