<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_plats' => [[], ['_controller' => 'App\\Controller\\PlatController::index'], [], [['text', '/plats']], [], [], []],
    'app_plat_new' => [[], ['_controller' => 'App\\Controller\\PlatController::addProduct'], [], [['text', '/plat/add']], [], [], []],
];
