<?php

namespace Container3lFu9P8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_U76tPZmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.u76tPZm' shared service.
     *
     * @return \App\Controller\ValidatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\PlatController::deletePlat()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ValidatorInterface". Did you forget to add a use statement?');
    }
}
