<?php

namespace Container3lFu9P8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JGcH0VVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jGcH0VV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jGcH0VV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'validator' => ['privates', '.errored.u76tPZm', NULL, 'Cannot determine controller argument for "App\\Controller\\PlatController::deletePlat()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ValidatorInterface". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'validator' => '?',
        ]);
    }
}
